get_job_in_germany:
    resource: "@GetJobInGermanyBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

app:
    resource: @AppBundle/Controller/
    type:     annotation
