services:
#    get_job_in_germany.example:
#        class: SkyResource\GetJobInGermanyBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    getjobingermany.twig.extension:
        class: SkyResource\GetJobInGermanyBundle\Twig\Extensions\GetJobInGermanyExtension
        tags:
            - { name: twig.extension }
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }